<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Facebook_Group_Ads\\' => array($baseDir . '/'),
    'Facebook\\' => array($vendorDir . '/facebook/graph-sdk/src/Facebook'),
);
